/**
 * example field map transform:
 * - camel case all field names
 * - transform 'Day' field to ISO 8601
 * - don't include monthYear, year, factionDate
 */
module.exports = entry => ({
  id: entry.GlobalEventID,
  day: `${entry.Day.slice(0,4)}-${entry.Day.slice(4,6)}-${entry.Day.slice(6,8)}`,
  // monthYear: entry.MonthYear,
  // year: entry.Year,
  // fractionDate: entry.FractionDate,
  actor1Code: entry.Actor1Code,
  actor1Name: entry.Actor1Name,
  actor1CountryCode: entry.Actor1CountryCode,
  actor1KnownGroupCode: entry.Actor1KnownGroupCode,
  actor1EthnicCode: entry.Actor1EthnicCode,
  actor1Religion1Code: entry.Actor1Religion1Code,
  actor1Religion2Code: entry.Actor1Religion2Code,
  actor1Type1Code: entry.Actor1Type1Code,
  actor1Type2Code: entry.Actor1Type2Code,
  actor1Type3Code: entry.Actor1Type3Code,
  actor2Code: entry.Actor2Code,
  actor2Name: entry.Actor2Name,
  actor2CountryCode: entry.Actor2CountryCode,
  actor2KnownGroupCode: entry.Actor2KnownGroupCode,
  actor2EthnicCode: entry.Actor2EthnicCode,
  actor2Religion1Code: entry.Actor2Religion1Code,
  actor2Religion2Code: entry.Actor2Religion2Code,
  actor2Type1Code: entry.Actor2Type1Code,
  actor2Type2Code: entry.Actor2Type2Code,
  actor2Type3Code: entry.Actor2Type3Code,
  isRootEvent: entry.IsRootEvent,
  eventCode: entry.EventCode,
  eventBaseCode: entry.EventBaseCode,
  eventRootCode: entry.EventRootCode,
  quadClass: entry.QuadClass,
  goldsteinScale: entry.GoldsteinScale,
  numMentions: entry.NumMentions,
  numSources: entry.NumSources,
  numArticles: entry.NumArticles,
  avgTone: entry.AvgTone,
  actor1Geo_Type: entry.Actor1Geo_Type,
  actor1Geo_Fullname: entry.Actor1Geo_Fullname,
  actor1Geo_CountryCode: entry.Actor1Geo_CountryCode,
  actor1Geo_ADM1Code: entry.Actor1Geo_ADM1Code,
  actor1Geo_ADM2Code: entry.Actor1Geo_ADM2Code,
  actor1Geo_Lat: entry.Actor1Geo_Lat,
  actor1Geo_Long: entry.Actor1Geo_Long,
  actor1Geo_FeatureID: entry.Actor1Geo_FeatureID,
  actor2Geo_Type: entry.Actor2Geo_Type,
  actor2Geo_Fullname: entry.Actor2Geo_Fullname,
  actor2Geo_CountryCode: entry.Actor2Geo_CountryCode,
  actor2Geo_ADM1Code: entry.Actor2Geo_ADM1Code,
  actor2Geo_ADM2Code: entry.Actor2Geo_ADM2Code,
  actor2Geo_Lat: entry.Actor2Geo_Lat,
  actor2Geo_Long: entry.Actor2Geo_Long,
  actor2Geo_FeatureID: entry.Actor2Geo_FeatureID,
  actionGeo_Type: entry.ActionGeo_Type,
  actionGeo_Fullname: entry.ActionGeo_Fullname,
  actionGeo_CountryCode: entry.ActionGeo_CountryCode,
  actionGeo_ADM1Code: entry.ActionGeo_ADM1Code,
  actionGeo_ADM2Code: entry.ActionGeo_ADM2Code,
  actionGeo_Lat: entry.ActionGeo_Lat,
  actionGeo_Long: entry.ActionGeo_Long,
  actionGeo_FeatureID: entry.ActionGeo_FeatureID,
  dateAdded: entry.DATEADDED,
  sourceURL: entry.SOURCEURL
});
