/**
 * example predicate map transform:
 * - transform 'Day' field to ISO 8601
 * - don't include monthYear, year, factionDate
 */

const eventURI = ({ GlobalEventID }) => `gdelt:${GlobalEventID}`;

module.exports = entry => ([
  { subject: eventURI(entry), predicate: 'rdf:type', object: 'gdelt:Event' },
  { subject: eventURI(entry), predicate: 'gdelt:date', object: `${entry.Day.slice(0,4)}-${entry.Day.slice(4,6)}-${entry.Day.slice(6,8)}` },
  // { subject: eventURI(entry), predicate: 'gdelt:month-year', object: '' },
  // { subject: eventURI(entry), predicate: 'gdelt:year', object: '' },
  // { subject: eventURI(entry), predicate: 'gdelt:factionDate', object: '' },
  { subject: eventURI(entry), predicate: 'gdelt:actor1Code', object: entry.Actor1Code },
  { subject: eventURI(entry), predicate: 'gdelt:actor1Name', object: entry.Actor1Name },
  { subject: eventURI(entry), predicate: 'gdelt:actor1CountryCode', object: entry.Actor1CountryCode },
  { subject: eventURI(entry), predicate: 'gdelt:actor1KnownGroup', object: entry.Actor1KnownGroupCode },
  { subject: eventURI(entry), predicate: 'gdelt:actor1EthnicCode', object: entry.Actor1EthnicCode },
  { subject: eventURI(entry), predicate: 'gdelt:actor1Religion1Code', object: entry.Actor1Religion1Code },
  { subject: eventURI(entry), predicate: 'gdelt:actor1Religion2Code', object: entry.Actor1Religion2Code },
  { subject: eventURI(entry), predicate: 'gdelt:actor1Type1Code', object: entry.Actor1Type1Code },
  { subject: eventURI(entry), predicate: 'gdelt:actor1Type2Code', object: entry.Actor1Type2Code },
  { subject: eventURI(entry), predicate: 'gdelt:actor1Type3Code', object: entry.Actor1Type3Code },
  { subject: eventURI(entry), predicate: 'gdelt:actor2Code', object: entry.Actor2Code },
  { subject: eventURI(entry), predicate: 'gdelt:actor2Name', object: entry.Actor2Name },
  { subject: eventURI(entry), predicate: 'gdelt:actor2CountryCode', object: entry.Actor2CountryCode },
  { subject: eventURI(entry), predicate: 'gdelt:actor2KnownGroup', object: entry.Actor2KnownGroupCode },
  { subject: eventURI(entry), predicate: 'gdelt:actor2EthnicCode', object: entry.Actor2EthnicCode },
  { subject: eventURI(entry), predicate: 'gdelt:actor2Religion1Code', object: entry.Actor2Religion1Code },
  { subject: eventURI(entry), predicate: 'gdelt:actor2Religion2Code', object: entry.Actor2Religion2Code },
  { subject: eventURI(entry), predicate: 'gdelt:actor2Type1Code', object: entry.Actor2Type1Code },
  { subject: eventURI(entry), predicate: 'gdelt:actor2Type2Code', object: entry.Actor2Type2Code },
  { subject: eventURI(entry), predicate: 'gdelt:actor2Type3Code', object: entry.Actor2Type3Code },
  { subject: eventURI(entry), predicate: 'gdelt:isRootEvent', object: entry.IsRootEvent },
  { subject: eventURI(entry), predicate: 'gdelt:eventCode', object: entry.EventCode },
  { subject: eventURI(entry), predicate: 'gdelt:eventBaseCode', object: entry.EventBaseCode },
  { subject: eventURI(entry), predicate: 'gdelt:eventRootCode', object: entry.EventRootCode },
  { subject: eventURI(entry), predicate: 'gdelt:quadClass', object: entry.QuadClass },
  { subject: eventURI(entry), predicate: 'gdelt:goldsteinScale', object: entry.GoldsteinScale },
  { subject: eventURI(entry), predicate: 'gdelt:numMentions', object: entry.NumMentions },
  { subject: eventURI(entry), predicate: 'gdelt:numSources', object: entry.NumSources },
  { subject: eventURI(entry), predicate: 'gdelt:numArticles', object: entry.NumArticles },
  { subject: eventURI(entry), predicate: 'gdelt:avgTone', object: entry.AvgTone },
  { subject: eventURI(entry), predicate: 'gdelt:actor1Geo_Type', object: entry.Actor1Geo_Type },
  { subject: eventURI(entry), predicate: 'gdelt:actor1Geo_Fullname', object: entry.Actor1Geo_Fullname },
  { subject: eventURI(entry), predicate: 'gdelt:actor1Geo_CountryCode', object: entry.Actor1Geo_CountryCode },
  { subject: eventURI(entry), predicate: 'gdelt:actor1Geo_ADM1Code', object: entry.Actor1Geo_ADM1Code },
  { subject: eventURI(entry), predicate: 'gdelt:actor1Geo_ADM2Code', object: entry.Actor1Geo_ADM2Code },
  { subject: eventURI(entry), predicate: 'gdelt:actor1Geo_Lat', object: entry.Actor1Geo_Lat },
  { subject: eventURI(entry), predicate: 'gdelt:actor1Geo_Long', object: entry.Actor1Geo_Long },
  { subject: eventURI(entry), predicate: 'gdelt:actor1Geo_FeatureID', object: entry.Actor1Geo_FeatureID },
  { subject: eventURI(entry), predicate: 'gdelt:actor2Geo_Type', object: entry.Actor2Geo_Type },
  { subject: eventURI(entry), predicate: 'gdelt:actor2Geo_Fullname', object: entry.Actor2Geo_Fullname },
  { subject: eventURI(entry), predicate: 'gdelt:actor2Geo_CountryCode', object: entry.Actor2Geo_CountryCode },
  { subject: eventURI(entry), predicate: 'gdelt:actor2Geo_ADM1Code', object: entry.Actor2Geo_ADM1Code },
  { subject: eventURI(entry), predicate: 'gdelt:actor2Geo_ADM2Code', object: entry.Actor2Geo_ADM2Code },
  { subject: eventURI(entry), predicate: 'gdelt:actor2Geo_Lat', object: entry.Actor2Geo_Lat },
  { subject: eventURI(entry), predicate: 'gdelt:actor2Geo_Long', object: entry.Actor2Geo_Long },
  { subject: eventURI(entry), predicate: 'gdelt:actor2Geo_FeatureID', object: entry.Actor2Geo_FeatureID },
  { subject: eventURI(entry), predicate: 'gdelt:actionGeo_Type', object: entry.ActionGeo_Type },
  { subject: eventURI(entry), predicate: 'gdelt:actionGeo_Fullname', object: entry.ActionGeo_Fullname },
  { subject: eventURI(entry), predicate: 'gdelt:actionGeo_CountryCode', object: entry.ActionGeo_CountryCode },
  { subject: eventURI(entry), predicate: 'gdelt:actionGeo_ADM1Code', object: entry.ActionGeo_ADM1Code },
  { subject: eventURI(entry), predicate: 'gdelt:actionGeo_ADM2Code', object: entry.ActionGeo_ADM2Code },
  { subject: eventURI(entry), predicate: 'gdelt:actionGeo_Lat', object: entry.ActionGeo_Lat },
  { subject: eventURI(entry), predicate: 'gdelt:actionGeo_Long', object: entry.ActionGeo_Long },
  { subject: eventURI(entry), predicate: 'gdelt:actionGeo_FeatureID', object: entry.ActionGeo_FeatureID },
  { subject: eventURI(entry), predicate: 'gdelt:dateAdded', object: entry.DATEADDED },
  { subject: eventURI(entry), predicate: 'gdelt:source_url', object: entry.SOURCEURL }
]);
